### ISSUE TITLE
wb-command cifti-math

### ISSUE THREAD

**Issue by Troudi-Abir** [sccn/fMRIb#8]
Hello,
I have downloaded the task analysis packages for working memory from https://db.humanconnectome.org, and I need to create the activation count maps, so I already have the zstat maps. Therefore, I will be using wb_command cifti-math for the steps above to make the activation count map, and wb_view to look at the maps.
I found some difficulties with using wb_command cifti-math, so Ineed an example of a command line executable for workbench to better understand the general structure of work?
I would really appreciate any help from you.
Best Regards,
Abir TROUDI

**Comment by arnodelorme** [comment]
Wrong toolbox see https://github.com/Washington-University/cifti-matlab
