### ISSUE TITLE
cifti-MATLAB

### ISSUE THREAD

**Issue by Troudi-Abir** [sccn/fMRIb#9]
Dear all,

I'm working on cifti files, and I need to read them with MATLAB, so I created these command lines ;

wbcmd='wb_command';
cifti = cifti_read(filename, 'wbcmd', wbcmd);
cifti.cdata=outputcifti;
figure,
imshow (outputcifti);

I've got these errors : Undefined function or variable 'myargparse'.

Error in cifti_read (line 11)
    options = myargparse(varargin, {'wbcmd'});

Error in ciftiopen (line 9)
    cifti = cifti_read(filename, 'wbcmd', wbcmd);

Error in TEST1 (line 5)
cii=ciftiopen('100307_tfMRI_WM_level2_0BK_hp200_s4_MSMAll.dscalar.nii');

Could you fix my script?
I would appreciate any help from you.

Thank you.

**Comment by arnodelorme** [comment]
Wrong toolbox see https://github.com/Washington-University/cifti-matlab
